"""04_fix_ins_length

Revision ID: 0b2fc869567f
Revises: 5e4e0cc7ae2f
Create Date: 2024-08-19 20:58:57.085155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2fc869567f'
down_revision: Union[str, None] = '5e4e0cc7ae2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instructions', 'title',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=640),
               existing_nullable=False)
    op.alter_column('instructions', 'number',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('instructions', 'filename',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=640),
               existing_nullable=True)
    op.drop_constraint('uix_2', 'journals', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_2', 'journals', ['user_uuid', 'instruction_id'])
    op.alter_column('instructions', 'filename',
               existing_type=sa.String(length=640),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('instructions', 'number',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('instructions', 'title',
               existing_type=sa.String(length=640),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
