"""06_make_histories_universal

Revision ID: 2502a9a8b7fd
Revises: 187f5910b321
Create Date: 2024-10-28 12:21:36.052531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '2502a9a8b7fd'
down_revision: Union[str, None] = '187f5910b321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

history_type_enum = ENUM('TEST_EXECUTION', 'DATE_RENEWAL', name='history_type_enum', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    history_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('histories', sa.Column('type', sa.Enum('TEST_EXECUTION', 'DATE_RENEWAL', name='history_type_enum'), server_default='DATE_RENEWAL', nullable=False))
    op.add_column('histories', sa.Column('instruction_id', sa.BigInteger(), nullable=True))
    op.add_column('histories', sa.Column('test_id', sa.BigInteger(), nullable=True))
    op.add_column('histories', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'histories', 'instructions', ['instruction_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'histories', 'tests', ['test_id'], ['id'], ondelete='SET NULL')
    op.drop_column('histories', 'instruction_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('instruction_title', sa.VARCHAR(length=640), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.drop_column('histories', 'additional_data')
    op.drop_column('histories', 'test_id')
    op.drop_column('histories', 'instruction_id')
    op.drop_column('histories', 'type')
    history_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
