"""05_journals_data_null_true

Revision ID: 286188e50c96
Revises: 0b2fc869567f
Create Date: 2024-08-24 10:13:02.232287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '286188e50c96'
down_revision: Union[str, None] = '0b2fc869567f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journals', 'last_date_read',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"))
    op.drop_constraint('journals_user_uuid_instruction_id_key', 'journals', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('journals_user_uuid_instruction_id_key', 'journals', ['user_uuid', 'instruction_id'])
    op.alter_column('journals', 'last_date_read',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"))
    # ### end Alembic commands ###
