"""03_add_journals

Revision ID: 5e4e0cc7ae2f
Revises: 2eb38f433f7d
Create Date: 2024-08-16 09:04:43.218637

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4e0cc7ae2f'
down_revision: Union[str, None] = '2eb38f433f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_uuid', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('instruction_id', sa.BigInteger(), nullable=False),
    sa.Column('last_date_read', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('signature', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'instruction_id', name='uix_2')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journals')
    # ### end Alembic commands ###
