"""07_add_divisions

Revision ID: 6bcb4ca020a6
Revises: d56468508da0
Create Date: 2024-08-28 07:27:13.771713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcb4ca020a6'
down_revision: Union[str, None] = 'd56468508da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('division_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user', 'divisions', ['division_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'division_id')
    op.drop_table('divisions')
    # ### end Alembic commands ###
