"""02_add_unique_title_prof

Revision ID: 9493cea7c525
Revises: e6e36fe74295
Create Date: 2024-09-04 19:13:01.795847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9493cea7c525'
down_revision: Union[str, None] = 'e6e36fe74295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'professions', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professions', type_='unique')
    # ### end Alembic commands ###
