"""04_add_table_histories

Revision ID: cbfcd5bceb7a
Revises: 8d8abc07e23f
Create Date: 2024-09-24 15:11:45.848885

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfcd5bceb7a'
down_revision: Union[str, None] = '8d8abc07e23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_uuid', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature', sa.String(length=320), nullable=True),
    sa.Column('instruction_title', sa.String(length=640), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    # ### end Alembic commands ###
