"""06_rename_prof_field

Revision ID: d56468508da0
Revises: 286188e50c96
Create Date: 2024-08-28 06:26:42.409396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56468508da0'
down_revision: Union[str, None] = '286188e50c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profession_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('user_profession_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'professions', ['profession_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user', 'profession')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profession', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_profession_fkey', 'user', 'professions', ['profession'], ['id'], ondelete='SET NULL')
    op.drop_column('user', 'profession_id')
    # ### end Alembic commands ###
