"""01_create_tables

Revision ID: e6e36fe74295
Revises: 
Create Date: 2024-08-29 06:02:39.191812

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e36fe74295'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('instructions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=640), nullable=False),
    sa.Column('number', sa.String(length=320), nullable=True),
    sa.Column('filename', sa.String(length=640), nullable=True),
    sa.Column('iteration', sa.Boolean(), nullable=False),
    sa.Column('period', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('professions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profession_id', sa.BigInteger(), nullable=False),
    sa.Column('instruction_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profession_id', 'instruction_id', name='uix_1')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('last_name', sa.String(length=320), nullable=False),
    sa.Column('father_name', sa.String(length=320), nullable=True),
    sa.Column('telegram_id', sa.String(length=320), nullable=True),
    sa.Column('phone_number', sa.String(length=320), nullable=True),
    sa.Column('profession_id', sa.BigInteger(), nullable=True),
    sa.Column('division_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('journals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_uuid', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('instruction_id', sa.BigInteger(), nullable=False),
    sa.Column('last_date_read', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'instruction_id', name='uix_2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journals')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('rules')
    op.drop_table('professions')
    op.drop_table('instructions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
