version: "2.2"

services:
  app:
    container_name: control_app
    image: akafer/ins_control
    restart: on-failure
    ports:
      - "8500:8500"
    command: >
      bash -c "alembic upgrade head
      && python3 /app/src/run.py --port=8500"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: control_db
    image: postgres:14-bullseye
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data: