# Stage 1: Build
FROM node:18-alpine as build

# Устанавливаем рабочую директорию
WORKDIR /frontend

# Устанавливаем необходимые пакеты
RUN apk add --no-cache \
    bash \
    curl \
    git \
    openssl \
    libssl1.1

# Копируем только необходимые файлы
COPY frontend/package.json /frontend/
RUN npm install

# Копируем исходный код
COPY frontend/src /frontend/src
COPY frontend/public /frontend/public

# Сборка фронтенда
RUN npm run build

# Stage 2: Final
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /frontend

# Копируем только собранный артефакт
COPY --from=build /frontend/build /frontend/build

# Устанавливаем только зависимости для продакшена
COPY frontend/package.json /frontend/
RUN npm install --production

# Запуск приложения
CMD ["npm", "start"]
