FROM node:18-slim as build

WORKDIR /frontend

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    openssl

COPY frontend/package.json frontend/package-lock.json /frontend/
RUN npm install

COPY frontend/src /frontend/src
COPY frontend/public /frontend/public
COPY frontend/nginx.conf /frontend/nginx.conf

RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /frontend/build /usr/share/nginx/html
COPY --from=build /frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
