version: "2.2"

services:
  db:
    container_name: control_db
    image: postgres:14-bullseye
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    container_name: control_app
    image: akafer/ins_control
    restart: on-failure
    ports:
      - "8500:8500"
    command: >
      bash -c "alembic upgrade head
      && python3 /app/src/run.py --port=8500"
    env_file:
      - .env
    volumes:
        - ./files:/app/src/static
    depends_on:
      db:
        condition: service_healthy

  worker:
    container_name: control_worker
    image: akafer/ins_control
    restart: on-failure
    command: >
       bash -c "tail -f /dev/null"
#      bash -c "cd jobs/
#      && python -m pwiz -e postgresql -u postgres db_control > models.py
#      && python3 /app/src/worker.py"
    env_file:
      - .env
    volumes:
      - ./files:/app/src/static
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: