FROM node:18-slim as build

# Устанавливаем рабочую директорию
WORKDIR /frontend

# Устанавливаем необходимые пакеты
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    openssl

# Копируем только необходимые файлы
COPY frontend/package.json /frontend/
RUN npm install

# Копируем исходный код
COPY frontend/src /frontend/src
COPY frontend/public /frontend/public

# Сборка фронтенда
RUN npm run build

# Stage 2: Final
FROM node:18-slim

# Устанавливаем рабочую директорию
WORKDIR /frontend

# Копируем только собранный артефакт
COPY --from=build /frontend/build /frontend/build

# Устанавливаем только зависимости для продакшена
COPY frontend/package.json /frontend/
RUN npm install --production

# Запуск приложения
CMD ["npm", "start"]
